# Generated by Django 5.0.3 on 2024-03-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='short',
            field=models.CharField(default='default_value', max_length=10),
        ),
    ]
