# Generated by Django 5.0.3 on 2024-03-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_region_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='short',
            field=models.CharField(default='default_value', max_length=10),
        ),
    ]
