# Generated by Django 5.0.3 on 2024-03-19 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_category_short'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Author',
        ),
    ]
